spring:
  cloud:
    # Spring Cloud Gateway 配置项，对应 GatewayProperties 类
    gateway:
      # 路由配置项，对应 RouteDefinition 数组
      routes:
        - id: ReactiveCompositeDiscoveryClient_user-service # 路由的编号
          uri: lb://lakers-family-service # 路由到的目标地址
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/user/**
          filters:
            - StripPrefix=1