# spring多模块依赖时，被依赖模块的配置文件不生效的问题解决
spring:
  cloud:
    stream:
      kafka:
        binder:
          # Kafka的服务端列表
          brokers: 172.23.3.19:9092,172.23.3.19:9093
          auto-add-partitions: true
          auto-create-topics: true
          min-partition-count: 1
      bindings:
        # 下面这里是配置各种消费的TOPIC 和生产的TOPIC
        input:
          desctionation: topic_name
          content-type: application/json
        output:
          destination: topic_name
          content-type: application/json
          producer:
            partitionCount: 1
        example-topic-input:
          content-type: application/json
          destination: kafkatopic
        example-topic-output:
          content-type: application/json
          destination: kafkatopic