spring:
  cache:
    # spring cache 缓存类型为redis  也可以是其他的实现
    type: redis
  redis:
    cluster:
      # 各 Redis 节点信息
      nodes:
        - 172.23.3.19:7001 # 127.0.0.1:7001
        - 172.23.3.19:7002 # 127.0.0.1:7002
        - 172.23.3.19:7003 # 127.0.0.1:7003
        - 172.23.3.19:7004 # 127.0.0.1:7004
        - 172.23.3.19:7005 # 127.0.0.1:7005
        - 172.23.3.19:7006 # 127.0.0.1:7006
      max-redirects: 3 # 获取失败 最大重定向次数
    lettuce:
      pool:
        max-active: 1000  #连接池最大连接数（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 5 # 连接池中的最小空闲连接
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）

  datasource:
    url: jdbc:mysql://172.23.3.19:3306/learning?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: test
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    instance-count: 1
    instance-index: 0
    stream:
      kafka:
        binder:
          brokers: 172.23.3.19:2889
          auto-add-partitions: true
          auto-create-topics: true
          min-partition-count: 1
      bindings:
        output:
          destination: messages
          content-type: application/json
          producer:
            partitionCount: 1




registry:
  servers:
    172.23.3.19:2181,172.23.3.19:2182,172.23.3.19:2183
