spring:
  cloud:
    instance-count: 1
    instance-index: 0
    stream:
      kafka:
        binder:
          brokers: 172.23.3.19:9092,172.23.3.19:9093
          auto-add-partitions: true
          auto-create-topics: true
          min-partition-count: 1
      bindings:
        output:
          destination: messages
          content-type: application/json
          producer:
            partitionCount: 1