spring:
  application:
    name: lakers-portal-service # Spring 应用名
  cloud:
    nacos:
      # Nacos 作为注册中心的配置项
      discovery:
        server-addr: 127.0.0.1:8848 # Nacos 服务器地址 "'lb://'+serviceId"

feign:
  okhttp:
    enabled: true #配置文件开启OpenFeign使用OkHttp作为底层的client

server:
  port: ${random.int[10000,19999]}  # 服务器端口。默认为 8080
  #port: ${random.int[10000,19999]}  # 服务器端口。默认为 8080
  #  port: 18080  # 服务器端口。默认为 8080





