spring:
  application:
    name: lakers-auth # Spring 应用名
  cloud:
    nacos:
      # Nacos 作为注册中心的配置项
      discovery:
        server-addr: 127.0.0.1:8848 # Nacos 服务器地址 "'lb://'+serviceId"
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  management:
    endpoints:
      web:
        exposure:
          include: "*"
server:
  port: ${random.int[10000,19999]}
  #  port: 18080  # 服务器端口。默认为 8080


jwt:
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY
  expiration: 86400